apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: eu.gcr.io/stromasys-projects/substra-frontend
      context: .
      docker:
        target: build

deploy:
  helm:
    releases:
      - name: frontend-org-1
        chartPath: charts/substra-frontend
        namespace: org-1
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/stromasys-projects/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-1.com
          service:
            type: LoadBalancer
            port: 80
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-1.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx

      - name: frontend-org-2
        chartPath: charts/substra-frontend
        namespace: org-2
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/stromasys-projects/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-2.com
          service:
            type: LoadBalancer
            port: 80
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-2.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx

      - name: frontend-org-3
        chartPath: charts/substra-frontend
        namespace: org-3
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/stromasys-projects/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-3.com
          service:
            type: LoadBalancer
            port: 80
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-3.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx

      - name: frontend-org-4
        chartPath: charts/substra-frontend
        namespace: org-4
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/stromasys-projects/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-4.com
          service:
            type: LoadBalancer
            port: 80
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-4.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx

    flags:
      install: ["--create-namespace"]
